site_name: eryz-os
site_url: https://mydomain.org/mysite
theme:
  name: material

use_directory_urls: false

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - blog.post_excerpt
  palette: 
    - scheme: default
      primary: deep green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: src/blue-kirby2.png
  favicon: src/blue-kirby2.png

plugins:
  - search
  - blog:
      post_url_format: "{slug}"
      post_excerpt: required
  - tags:
      tags_file: tags.md

nav:
  - Home: index.md
  # - About: 
  #     - About me: about/about.md
  # - Tags: tags.md

repo_url: https://github.com/GabriellaGloria/eryz-os
repo_name: GabriellaGloria/eryz-os

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex
  - toc:
      permalink: true
